// Useful, topic-specific copy. No invented prices, offices or arrival times.
export const serviceGuides = {
  tow: {
    bg: { title: 'Репатрак и пътна помощ 24/7 | Бетина 97', description: 'Репатриране на леки и лекотоварни автомобили в Ботевград, Правец, Мездра и АМ Хемус. Превоз до избран сервиз. Безплатна оферта: 0878 558 152.', when: ['Автомобилът е аварирал и не може да продължи пътуването.', 'Повредени или блокирали колела затрудняват преместването.', 'Нужен е предварително уговорен превоз до сервиз или адрес.'], prepare: ['Марка, модел и вид на автомобила.', 'Точна локация, достъп до автомобила и състояние на колелата.', 'Желан сервиз или адрес за разтоварване.'], extra: 'Крайното място за разтоварване се избира с вас. При превоз извън основния район уточняваме целия маршрут предварително. Цената зависи от мястото, дистанцията и условията за товарене.', faq: [['Може ли автомобилът да бъде превозен до моя сервиз?', 'Да, дестинацията се уговаря с вас. Посочете сервиза или адреса при заявката, за да включим маршрута в офертата.'], ['Какво да кажа при блокирали колела?', 'Уточнете кои колела не се движат и дали автомобилът може да бъде преместен. Това помага да се прецени подходящото оборудване.']] },
    en: { title: 'Flatbed Towing & Roadside Assistance | Betina 97', description: 'Passenger car and light van recovery in Botevgrad, Pravets, Mezdra and on Hemus. Transport to your chosen workshop. Free quote: +359 878 558 152.', when: ['The vehicle has broken down and cannot continue its journey.', 'Damaged or locked wheels make moving the vehicle difficult.', 'You need pre-arranged transport to a workshop or address.'], prepare: ['Vehicle make, model and type.', 'Exact location, vehicle access and wheel condition.', 'Your chosen workshop or unloading address.'], extra: 'The unloading destination is agreed with you. For transport beyond the main service area, we discuss the whole route beforehand. The price depends on location, distance and loading conditions.', faq: [['Can you transport my vehicle to my own workshop?', 'Yes, the destination is agreed with you. Include the workshop or address in your request so the route can be included in the quote.'], ['What should I mention if the wheels are locked?', 'Tell us which wheels cannot move and whether the vehicle can be repositioned. This helps us assess appropriate equipment.']] }
  },
  tire: {
    bg: { title: 'Помощ при спукана гума, ремонт и смяна | Бетина 97', description: 'Помощ при спукана гума в района на Ботевград, Правец, Мездра и АМ Хемус. Смяна с резервна гума или съдействие за сервиз. Обадете се на 0878 558 152.', when: ['Имате спукана гума и подходяща резервна гума.', 'Нямате резервна гума или повредата изисква сервиз.', 'Не сте сигурни дали е възможна помощ на място.'], prepare: ['Марка, модел и местоположение на автомобила.', 'Коя гума е повредена и дали има изправна резервна.', 'Размерът на гумата, ако го знаете, и достъпът до автомобила.'], extra: 'Смяната с резервна гума и ремонтът са различни услуги. Ремонтът може да изисква оборудване в сервиз за гуми. По телефона уточняваме възможното решение, наличността и дали е необходим транспорт.', faq: [['Извършвате ли всеки ремонт на гума на пътя?', 'Възможността зависи от повредата и условията. Обсъждаме смяна с подходяща резервна гума или съдействие за ремонт в сервиз.'], ['Какво става, ако нямам резервна гума?', 'Кажете ни още при разговора. Ще обсъдим подходящо съдействие или превоз до сервиз за гуми.']] },
    en: { title: 'Flat Tire Help, Repair & Replacement | Betina 97', description: 'Flat tire help around Botevgrad, Pravets, Mezdra and Hemus. Spare wheel fitting or assistance with workshop repair. Call +359 878 558 152.', when: ['You have a flat tire and a suitable spare wheel.', 'No spare is available or the damage requires a workshop.', 'You are unsure whether roadside help is possible.'], prepare: ['Vehicle make, model and location.', 'Which tire is damaged and whether a usable spare is available.', 'Tire size, if known, and access to the vehicle.'], extra: 'Spare wheel fitting and tire repair are different services. A repair may require equipment at a tire workshop. We discuss the suitable option, availability and any transport needed by phone.', faq: [['Can every tire repair be done at the roadside?', 'It depends on the damage and conditions. We discuss fitting a suitable spare or help with a workshop repair.'], ['What if I do not have a spare wheel?', 'Mention it when you call. We will discuss appropriate assistance or transport to a tire workshop.']] }
  },
  battery: {
    bg: { title: 'Подаване на ток и помощ при акумулатор | Бетина 97', description: 'Помощ при изтощен акумулатор и проблем със стартиране в Ботевград и района. Подаване на ток според случая. Уточнете наличността на 0878 558 152.', when: ['Автомобилът не стартира след престой.', 'Има симптоми на изтощен акумулатор.', 'Не е ясно дали проблемът е в акумулатора или друг компонент.'], prepare: ['Марка, модел и тип на автомобила.', 'Какво се случва при опит за стартиране.', 'Местоположение и възможност за достъп до автомобила.'], extra: 'Не всеки проблем със стартирането се решава с подаване на ток. Опишете симптомите, за да уточним дали тази помощ е подходяща. При друга повреда можем да обсъдим транспорт до сервиз.', faq: [['Гарантира ли подаването на ток, че автомобилът ще запали?', 'Не. Причината може да е различна от изтощен акумулатор. Преценяваме ситуацията според симптомите и вида на автомобила.'], ['Как да заявя помощ за конкретен модел?', 'Посочете марката, модела и симптомите в бележките на заявката или ги опишете по телефон.']] },
    en: { title: 'Battery & Jump-Start Assistance | Betina 97', description: 'Help with flat batteries and starting problems around Botevgrad. Jump-start assistance where suitable. Confirm availability: +359 878 558 152.', when: ['Your vehicle will not start after being parked.', 'There are symptoms of a flat battery.', 'You are unsure whether the battery or another component is involved.'], prepare: ['Vehicle make, model and type.', 'What happens when you try to start it.', 'Location and access to the vehicle.'], extra: 'Not every starting problem can be solved by a jump-start. Describe the symptoms so we can discuss whether it is suitable. For another fault, workshop transport can be discussed.', faq: [['Does a jump-start guarantee the vehicle will start?', 'No. The cause may be something other than a flat battery. We assess the situation based on symptoms and vehicle type.'], ['How do I request help for a particular model?', 'Include the make, model and symptoms in your request notes or explain them by phone.']] }
  },
  express: {
    bg: { title: 'Експресна пътна помощ и приоритетно посещение | Бетина 97', description: 'Заявете приоритетна пътна помощ в Ботевград, Правец, Мездра и АМ Хемус. Времето и цената се потвърждават според наличността: 0878 558 152.', when: ['Нуждаете се от бързо уточнение за възможно посещение.', 'Автомобилът е аварирал и времето е от значение.', 'Искате приоритетно посещение за конкретна услуга.'], prepare: ['Точното място и кратко описание на повредата.', 'Видът автомобил и каква помощ е необходима.', 'Телефон, на който може да се свържем с вас.'], extra: 'Експресното посещение е заявка за приоритет, а не обещание за фиксиран брой минути. Времето зависи от разстоянието, трафика и наличността. При спешна заявка директният разговор е най-бързият начин да уточним възможностите.', faq: [['Мога ли да добавя приоритет към друга услуга?', 'Да. В детайлите на заявката има опция за приоритетно посещение. Потвърждаваме възможността и цената по телефон.'], ['Има ли гарантиран срок за пристигане?', 'Не посочваме универсален срок. Възможното време за конкретната локация се обсъжда при разговора.']] },
    en: { title: 'Express Roadside Help & Priority Visits | Betina 97', description: 'Request priority roadside assistance in Botevgrad, Pravets, Mezdra and Hemus. Timing and price confirmed subject to availability: +359 878 558 152.', when: ['You need a quick discussion of possible attendance.', 'The vehicle has broken down and timing matters.', 'You want a priority visit for a particular service.'], prepare: ['Exact location and a short explanation of the problem.', 'Vehicle type and the assistance needed.', 'A phone number where we can reach you.'], extra: 'Express assistance is a request for priority, not a fixed-minute arrival promise. Timing depends on distance, traffic and availability. Calling directly is the quickest way to discuss urgent requests.', faq: [['Can I add priority to another service?', 'Yes. The request details include a priority visit option. We confirm availability and price by phone.'], ['Is there a guaranteed arrival time?', 'We do not give a universal time guarantee. A possible arrival time for your location is discussed when you call.']] }
  },
  fuel: {
    bg: { title: 'Доставка на гориво на пътя | Бетина 97', description: 'Останали сте без гориво около Ботевград, Правец, Мездра или АМ Хемус? Обсъдете доставка и наличност на 0878 558 152. Оферта преди посещение.', when: ['Останали сте без гориво и не можете да продължите.', 'Необходима е доставка до конкретно място.', 'Искате да уточните възможността и общата цена.'], prepare: ['Бензин или дизел и данни за автомобила.', 'Точна локация, посока на движение и ориентир.', 'Телефон за контакт и необходимото количество, ако го знаете.'], extra: 'Наличността, видът и количеството гориво се уточняват по телефон. Офертата включва уточнение за горивото и услугата по доставката. Ако доставка не е подходящото решение, обсъждаме друга възможност за помощ.', faq: [['Включва ли офертата самото гориво?', 'Преди посещението уточняваме отделно горивото и услугата, за да е ясна общата цена.'], ['Какво да посоча в заявката?', 'Напишете вида гориво, автомобила, точната локация и телефон за контакт. Не изпращайте заявка без да уточните бензин или дизел.']] },
    en: { title: 'Roadside Fuel Delivery | Betina 97', description: 'Out of fuel near Botevgrad, Pravets, Mezdra or Hemus? Discuss delivery and availability on +359 878 558 152. Quote agreed before attendance.', when: ['You have run out of fuel and cannot continue.', 'Fuel needs to be delivered to a specific location.', 'You want to confirm availability and the total price.'], prepare: ['Petrol or diesel and vehicle details.', 'Exact location, travel direction and a landmark.', 'Contact phone and the required quantity, if known.'], extra: 'Fuel availability, type and quantity are discussed by phone. The quote explains both the fuel and delivery service costs. If delivery is not a suitable solution, we discuss another option.', faq: [['Does the quote include the fuel itself?', 'We discuss the fuel and delivery service separately before attending so the total price is clear.'], ['What should I include in the request?', 'State the fuel type, vehicle, exact location and contact phone. Specify petrol or diesel.']] }
  },
  recovery: {
    bg: { title: 'Извличане на заседнал автомобил и транспорт | Бетина 97', description: 'Извличане с лебедка според условията и уговорен транспорт на автомобил в района на Ботевград. Опишете достъпа и повредата на 0878 558 152.', when: ['Автомобилът е заседнал и не може да се придвижи.', 'Повреди или блокирали колела затрудняват товаренето.', 'Нужен е специално уговорен превоз на автомобил.'], prepare: ['Описание на мястото, терена и достъпа за техника.', 'Състояние на автомобила, колелата и възможност за преместване.', 'Крайна точка за превоз и телефон за контакт.'], extra: 'При извличане достъпът и условията на терена имат значение за необходимата техника. Описанието по телефон помага да уточним възможното решение и цената. Не заявяваме еднакво оборудване за всяка ситуация.', faq: [['Може ли да се извлече всеки заседнал автомобил?', 'Възможността зависи от достъпа, терена, теглото и състоянието. Необходима е предварителна преценка по телефон.'], ['Каква е разликата с обикновено репатриране?', 'При извличане първо е необходимо автомобилът да бъде освободен или преместен до подходящо място за товарене. Това може да изисква допълнителна техника и време.']] },
    en: { title: 'Stuck Vehicle Recovery & Transport | Betina 97', description: 'Winch recovery where conditions allow and arranged vehicle transport around Botevgrad. Explain access and vehicle condition: +359 878 558 152.', when: ['Your vehicle is stuck and cannot move.', 'Damage or locked wheels make loading difficult.', 'You need specifically arranged vehicle transport.'], prepare: ['A description of the location, ground and equipment access.', 'Vehicle and wheel condition, and whether it can be repositioned.', 'Transport destination and a contact phone.'], extra: 'Equipment access and ground conditions affect recovery options. Your description helps us discuss a suitable solution and price. The same equipment is not appropriate for every situation.', faq: [['Can every stuck vehicle be recovered?', 'It depends on access, ground, weight and vehicle condition. A discussion by phone is needed to assess the situation.'], ['How does recovery differ from ordinary towing?', 'Recovery may first require freeing or moving the vehicle to a suitable loading location. This can require additional equipment and time.']] }
  }
};
export const regionGuides = {
  razliv: {
    bg: {
      title: 'Пътна помощ Разлив и района | Бетина 97',
      heading: 'Пътна помощ в Разлив и района',
      description: 'Автомобилът ви е аварирал в Разлив или наблизо? Денонощна връзка с Бетина 97 за репатрак и пътна помощ в района на Правец: 0878 558 152.',
      intro: 'Автомобилът ви е аварирал в Разлив или на път наблизо? Обадете се на Бетина 97 от Ботевград, за да уточним нужната помощ, цената и възможното време за посещение. Разлив е в община Правец; наличността се потвърждава по телефон.',
      heading2: 'Къде около Разлив е автомобилът?',
      text: 'Уточнете дали сте на улица в селото, на паркинг или на път извън него. Ако се движите към Ботевград или Правец, посочете посоката и видим ориентир. Ако всъщност сте на АМ „Хемус“, съобщете магистралата, километъра и посоката — името на близко село не е достатъчно за точна локация.',
      prepare: ['Разлив, община Правец, и улица, ориентир или GPS точка.', 'Пътят и посоката на движение, ако сте извън селото.', 'Каква е повредата, марка и модел на автомобила и достъпът до него.', 'Желан сервиз или адрес, ако е необходим превоз.'],
      focus: ['tow', 'tire', 'battery'],
      faq: [
        ['Трябва ли да знам точния адрес около Разлив?', 'Не е задължително да знаете адрес, но трябва да уточним мястото. Споделете GPS точка през картата или опишете пътя, посоката и най-близкия видим ориентир.'],
        ['Колко време отнема посещението до Разлив?', 'Възможното време се уточнява по телефон според точната локация, достъпа, трафика и текущата наличност. Обадете се директно при спешна заявка.'],
        ['Може ли превоз до избран от мен сервиз?', 'При заявка за репатрак посочете сервиза или адреса. Обсъждаме маршрута, условията за товарене и цената преди посещението.']
      ]
    },
    en: {
      title: 'Roadside Assistance Near Razliv | Betina 97',
      heading: 'Roadside assistance near Razliv',
      description: 'Car broken down in or near Razliv? Contact Betina 97 24/7 for towing and roadside help in the Pravets area. Confirm availability: +359 878 558 152.',
      intro: 'Car broken down in Razliv or on a nearby road? Call Betina 97, based in Botevgrad, to discuss the help you need, the price and a possible arrival time. Razliv is in Pravets municipality; availability is confirmed by phone.',
      heading2: 'Where near Razliv is your vehicle?',
      text: 'Tell us whether you are on a village street, in a parking area or on a road outside Razliv. If travelling towards Botevgrad or Pravets, give the direction and a visible landmark. If you are actually on the Hemus motorway, give the motorway name, kilometer marker and direction — naming a nearby village does not pinpoint the vehicle.',
      prepare: ['Razliv, Pravets municipality, plus a street, landmark or GPS point.', 'Road name and travel direction if outside the village.', 'The problem, vehicle make and model, and access to the vehicle.', 'Your chosen workshop or address if transport is needed.'],
      focus: ['tow', 'tire', 'battery'],
      faq: [
        ['Do I need an exact address near Razliv?', 'You do not have to know an address, but we need to identify the location. Share a GPS point through the map or describe the road, travel direction and nearest visible landmark.'],
        ['How long does attendance near Razliv take?', 'A possible arrival time is discussed by phone based on the exact location, access, traffic and current availability. Call directly for urgent requests.'],
        ['Can my vehicle be taken to my chosen workshop?', 'Include the workshop or address in your towing request. We discuss the route, loading conditions and price before attending.']
      ]
    }
  },
  botevgrad: {
    bg: { heading: 'Пътна помощ в Ботевград', description: 'Денонощна пътна помощ и репатрак в Ботевград от Бетина 97. Уточнете превоз до сервиз, спукана гума или помощ при стартиране: 0878 558 152.', intro: 'Ботевград е базовият район на Бетина 97. Ако автомобилът ви е аварирал в града, посочете улица, адрес или ясен ориентир, за да уточним достъпа и нужната помощ.', heading2: 'От градски адрес до избрания сервиз', text: 'При повреда на адрес, паркинг или в близост до града уточнете дали има ограничения за достъп и дали автомобилът може да бъде преместен. За репатриране посочете избрания сервиз или място за разтоварване още при разговора.', prepare: ['Улица, адрес или ориентир в Ботевград.', 'Достъп до паркинга и състояние на автомобила.', 'Адрес на сервиза или крайна точка за превоз.'], focus: ['tow','tire','battery'] },
    en: { heading: 'Roadside assistance in Botevgrad', description: '24/7 roadside help and towing in Botevgrad from Betina 97. Discuss workshop transport, flat tire or starting assistance: +359 878 558 152.', intro: 'Botevgrad is Betina 97’s base service area. If your vehicle has broken down in town, provide a street, address or clear landmark so we can discuss access and the help needed.', heading2: 'From a town address to your chosen workshop', text: 'For a breakdown at an address, car park or near town, explain any access restrictions and whether the vehicle can be moved. For towing, give your chosen workshop or unloading point when you call.', prepare: ['Street, address or landmark in Botevgrad.', 'Car park access and the condition of the vehicle.', 'Workshop address or final transport destination.'], focus: ['tow','tire','battery'] }
  },
  pravets: {
    bg: { heading: 'Пътна помощ в Правец', description: 'Пътна помощ в Правец и района: репатрак, помощ при спукана гума и уговорен превоз. Уточнете точна локация и наличност с Бетина 97 на 0878 558 152.', intro: 'Обслужваме заявки за пътна помощ в района на Правец. Уточнете дали автомобилът е в населено място или на път, както и точната локация, за да не се обърка мястото на повредата.', heading2: 'В града или на път към Правец?', text: 'Ако сте на път, посочете ориентир и посоката на движение. Ако сте на автомагистрала „Хемус“, добавете километър или близък пътен възел. Името на града само по себе си невинаги е достатъчно за намиране на автомобила.', prepare: ['Адрес в Правец или точни GPS координати.', 'Път и посока, ако сте извън града.', 'Километър или ориентир при заявка от АМ „Хемус“.'], focus: ['tow','tire','express'] },
    en: { heading: 'Roadside assistance in Pravets', description: 'Roadside assistance around Pravets: towing, flat tire help and arranged transport. Confirm your location and availability with Betina 97: +359 878 558 152.', intro: 'We handle roadside assistance requests around Pravets. Tell us whether the vehicle is in town or on a road, along with an exact location, to avoid confusion about the breakdown point.', heading2: 'In town or travelling towards Pravets?', text: 'On a road, provide a landmark and travel direction. On the Hemus motorway, add a kilometer marker or nearby junction. The town name alone may not be enough to locate the vehicle.', prepare: ['Pravets address or exact GPS coordinates.', 'Road and direction if outside town.', 'Kilometer marker or landmark for a Hemus request.'], focus: ['tow','tire','express'] }
  },
  mezdra: {
    bg: { heading: 'Пътна помощ в Мездра', description: 'Репатрак и пътна помощ в района на Мездра. Превоз на леки и лекотоварни автомобили до уговорено място. Безплатна оферта от Бетина 97: 0878 558 152.', intro: 'Мездра е част от основния район на обслужване. При заявка за репатрак уточняваме мястото за вземане на автомобила и целия маршрут до желания сервиз или адрес.', heading2: 'Ясен маршрут за автомобила ви', text: 'Ако крайната точка е в друго населено място, посочете я предварително. За уговорен транспорт уточнете дали автомобилът е в движение, състоянието на колелата и възможността за товарене. Наличността и времето се потвърждават за конкретния маршрут.', prepare: ['Адрес или GPS точка в района на Мездра.', 'Дестинация за превоз — сервиз, адрес или населено място.', 'Състояние на автомобила и условия за товарене.'], focus: ['tow','recovery','battery'] },
    en: { heading: 'Roadside assistance in Mezdra', description: 'Towing and roadside assistance around Mezdra. Passenger cars and light vans transported to an agreed destination. Free quote from Betina 97: +359 878 558 152.', intro: 'Mezdra is part of the main service area. For a tow request, we confirm the collection point and the complete route to your chosen workshop or address.', heading2: 'A clear route for your vehicle', text: 'If the destination is in another town, tell us beforehand. For arranged transport, explain whether the vehicle can move, its wheel condition and loading access. Availability and timing are confirmed for the specific route.', prepare: ['Address or GPS point around Mezdra.', 'Transport destination — workshop, address or town.', 'Vehicle condition and loading access.'], focus: ['tow','recovery','battery'] }
  },
  hemus: {
    bg: { heading: 'Пътна помощ на АМ „Хемус“', description: 'Пътна помощ и репатрак на АМ Хемус в района на Ботевград и Правец. Посочете километър и посока. Денонощна връзка с Бетина 97: 0878 558 152.', intro: 'Обслужваме автомагистрала „Хемус“ в основния район на Ботевград и Правец. При заявка от магистралата точната позиция и посоката на движение са особено важни.', heading2: 'Километър, посока и ориентир', text: 'За да уточним къде се намирате, кажете посоката на движение, километъра или близък пътен възел, тунел или друг видим ориентир. GPS координатите могат да се добавят към SMS заявката през интерактивната карта на сайта.', prepare: ['АМ „Хемус“ и посока на движение.', 'Километър, близък пътен възел или ориентир.', 'GPS точка, вид на автомобила и кратко описание на повредата.'], focus: ['tow','tire','express','fuel'] },
    en: { heading: 'Roadside assistance on the Hemus motorway', description: 'Hemus motorway towing and roadside assistance around Botevgrad and Pravets. Give a kilometer marker and travel direction. Call Betina 97 24/7: +359 878 558 152.', intro: 'We serve the Hemus motorway within the main Botevgrad and Pravets area. For motorway requests, the exact position and direction of travel are particularly important.', heading2: 'Kilometer marker, direction and landmark', text: 'Give your travel direction and a kilometer marker, nearby junction, tunnel or another visible landmark. GPS coordinates can be added to an SMS request using the website’s interactive map.', prepare: ['Hemus motorway and direction of travel.', 'Kilometer marker, nearby junction or landmark.', 'GPS point, vehicle type and a short description of the problem.'], focus: ['tow','tire','express','fuel'] }
  }
};
